# Generated by Django 4.2.5 on 2023-09-25 09:06

from django.db import migrations
import users.user_manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.user_manager.UserManager()),
            ],
        ),
    ]
