# Generated by Django 4.2.5 on 2023-09-26 23:51

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['first_name', 'last_name', 'hospital_id']),
        ),
    ]
