# Generated by Django 4.2.5 on 2023-09-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Indicate if user is a doctor'),
        ),
    ]
